name: Generate 3D Contribution Skyline

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  
  # Allows manual workflow run
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D GitHub Contribution Skyline
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate 3D Contribution Skyline
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D contribution skyline" || exit 0
          git push
